branch-defaults:
  main:
    environment: Tap-In-Closet-dev
    group_suffix: null
environment-defaults:
  Tap-In-Closet-dev:
    branch: null
    repository: null
global:
  application_name: Tap-In-Closet
  branch: null
  default_ec2_keyname: Create new KeyPair
  default_platform: Node.js 18 running on 64bit Amazon Linux 2023
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
